# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FYPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.0.2'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'ReachabilitySwift'
  # Pods for FYPlayer

end
